repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["-C", ".", "--baseline", ".secrets.baseline"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: end-of-file-fixer

  # Nutze das systemweit installierte gitleaks statt der eingebetteten Version
  - repo: local
    hooks:
      - id: gitleaks-system
        name: gitleaks (system)
        entry: gitleaks protect --staged --redact
        language: system
        pass_filenames: false
        stages: [commit, push]
